# Generated by Django 5.2.7 on 2025-11-08 02:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=50, verbose_name="品牌")),
                ("series", models.CharField(max_length=100, verbose_name="车系")),
                ("fuel_type", models.CharField(max_length=20, verbose_name="燃料类型")),
                ("seats", models.IntegerField(verbose_name="座位数")),
                ("car_type", models.CharField(max_length=50, verbose_name="车型")),
                (
                    "official_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="厂商报价(万)"
                    ),
                ),
                (
                    "dealer_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="经销商报价(万)"
                    ),
                ),
                ("comfort_score", models.FloatField(verbose_name="舒适性评分")),
                ("appearance_score", models.FloatField(verbose_name="外观评分")),
                ("config_score", models.FloatField(verbose_name="配置评分")),
                ("control_score", models.FloatField(verbose_name="操控评分")),
                ("power_score", models.FloatField(verbose_name="动力评分")),
                ("space_score", models.FloatField(verbose_name="空间评分")),
                ("interior_score", models.FloatField(verbose_name="内饰评分")),
                ("total_score", models.FloatField(verbose_name="总分")),
                ("image_urls", models.TextField(verbose_name="外观图片链接")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "汽车信息",
                "verbose_name_plural": "汽车信息",
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("质量问题", "质量问题"),
                            ("服务问题", "服务问题"),
                            ("其他问题", "其他问题"),
                        ],
                        max_length=20,
                        verbose_name="问题类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="投诉内容")),
                ("complaint_time", models.DateField(verbose_name="投诉时间")),
                ("tags", models.CharField(max_length=200, verbose_name="投诉标签")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="cars.car",
                        verbose_name="关联汽车",
                    ),
                ),
            ],
            options={
                "verbose_name": "投诉数据",
                "verbose_name_plural": "投诉数据",
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.CharField(max_length=7, verbose_name="年月")),
                ("sales_volume", models.IntegerField(verbose_name="销量(辆)")),
                ("rank", models.IntegerField(verbose_name="当月排名")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="cars.car",
                        verbose_name="关联汽车",
                    ),
                ),
            ],
            options={
                "verbose_name": "销量数据",
                "verbose_name_plural": "销量数据",
                "unique_together": {("car", "year_month")},
            },
        ),
    ]
