# Generated by Django 4.2.7 on 2025-11-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="品牌名称"
                    ),
                ),
                (
                    "logo",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="品牌Logo"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="国家"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "品牌",
                "verbose_name_plural": "品牌",
                "db_table": "brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="车系名称")),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("BEV", "纯电动"),
                            ("PHEV", "插电混动"),
                            ("HEV", "混合动力"),
                        ],
                        default="BEV",
                        max_length=10,
                        verbose_name="能源类型",
                    ),
                ),
                (
                    "price_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最低价格(万元)",
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最高价格(万元)",
                    ),
                ),
                (
                    "endurance_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最低续航(km)"
                    ),
                ),
                (
                    "endurance_max",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最高续航(km)"
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="车身类型"
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="车系图片"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="车系描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="cars.brand",
                        verbose_name="品牌",
                    ),
                ),
            ],
            options={
                "verbose_name": "车系",
                "verbose_name_plural": "车系",
                "db_table": "car_series",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(max_length=100, verbose_name="问题类型"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="问题描述"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "轻微"), ("medium", "中等"), ("high", "严重")],
                        default="medium",
                        max_length=10,
                        verbose_name="严重程度",
                    ),
                ),
                (
                    "report_count",
                    models.IntegerField(default=1, verbose_name="投诉次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上报时间"),
                ),
                (
                    "car_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="cars.carseries",
                        verbose_name="车系",
                    ),
                ),
            ],
            options={
                "verbose_name": "质量问题",
                "verbose_name_plural": "质量问题",
                "db_table": "car_issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(max_length=7, verbose_name="月份(格式: 2024-01)"),
                ),
                ("sales", models.IntegerField(default=0, verbose_name="销量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "car_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="cars.carseries",
                        verbose_name="车系",
                    ),
                ),
            ],
            options={
                "verbose_name": "销量数据",
                "verbose_name_plural": "销量数据",
                "db_table": "car_sales",
                "ordering": ["-month", "-sales"],
                "unique_together": {("car_series", "month")},
            },
        ),
    ]
