# Generated by Django 4.2.7 on 2025-11-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carissue",
            name="category",
            field=models.CharField(
                choices=[
                    ("quality", "质量问题"),
                    ("service", "服务问题"),
                    ("other", "其他问题"),
                ],
                default="quality",
                max_length=20,
                verbose_name="问题分类",
            ),
        ),
    ]
