# Generated by Django 4.2.7 on 2025-12-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_carissue_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="carseries",
            name="acceleration",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="百公里加速(s)"
            ),
        ),
        migrations.AddField(
            model_name="carseries",
            name="curb_weight",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="整备质量(kg)"
            ),
        ),
        migrations.AddField(
            model_name="carseries",
            name="drive_type",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="驱动方式"
            ),
        ),
        migrations.AddField(
            model_name="carseries",
            name="max_speed",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="最高车速(km/h)"
            ),
        ),
        migrations.AddField(
            model_name="carseries",
            name="score_appearance",
            field=models.DecimalField(
                decimal_places=1, default=4.0, max_digits=3, verbose_name="外观评分"
            ),
        ),
        migrations.AddField(
            model_name="carseries",
            name="score_comfort",
            field=models.DecimalField(
                decimal_places=1, default=4.0, max_digits=3, verbose_name="舒适性评分"
            ),
        ),
        migrations.AddField(
            model_name="carseries",
            name="score_config",
            field=models.DecimalField(
                decimal_places=1, default=4.0, max_digits=3, verbose_name="配置评分"
            ),
        ),
        migrations.AddField(
            model_name="carseries",
            name="score_interior",
            field=models.DecimalField(
                decimal_places=1, default=4.0, max_digits=3, verbose_name="内饰评分"
            ),
        ),
        migrations.AddField(
            model_name="carseries",
            name="score_power",
            field=models.DecimalField(
                decimal_places=1, default=4.0, max_digits=3, verbose_name="动力评分"
            ),
        ),
        migrations.AddField(
            model_name="carseries",
            name="score_space",
            field=models.DecimalField(
                decimal_places=1, default=4.0, max_digits=3, verbose_name="空间评分"
            ),
        ),
        migrations.AddField(
            model_name="carseries",
            name="seat_count",
            field=models.IntegerField(default=5, verbose_name="座位数"),
        ),
        migrations.AddField(
            model_name="carseries",
            name="wheelbase",
            field=models.IntegerField(blank=True, null=True, verbose_name="轴距(mm)"),
        ),
        migrations.CreateModel(
            name="CarVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="版本名称")),
                ("year", models.IntegerField(verbose_name="年份")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格(万元)"
                    ),
                ),
                (
                    "endurance",
                    models.IntegerField(blank=True, null=True, verbose_name="续航(km)"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认版本"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "car_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="cars.carseries",
                        verbose_name="车系",
                    ),
                ),
            ],
            options={
                "verbose_name": "车型版本",
                "verbose_name_plural": "车型版本",
                "db_table": "car_versions",
                "ordering": ["-year", "price"],
            },
        ),
        migrations.CreateModel(
            name="CarColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="颜色名称")),
                (
                    "color_code",
                    models.CharField(max_length=20, verbose_name="颜色代码"),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="该颜色车辆图片",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认颜色"),
                ),
                (
                    "car_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="cars.carseries",
                        verbose_name="车系",
                    ),
                ),
            ],
            options={
                "verbose_name": "车身颜色",
                "verbose_name_plural": "车身颜色",
                "db_table": "car_colors",
            },
        ),
    ]
