"""Create car related tables

Revision ID: 121b587a7eb5
Revises: 
Create Date: 2025-11-13 17:22:27.260151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121b587a7eb5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False, comment='品牌ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='品牌名称'),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='品牌Logo URL'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('car_series',
    sa.Column('id', sa.Integer(), nullable=False, comment='车系ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='车系名称'),
    sa.Column('brand_id', sa.Integer(), nullable=False, comment='品牌ID'),
    sa.Column('price_min', sa.Float(), nullable=True, comment='最低价格(万元)'),
    sa.Column('price_max', sa.Float(), nullable=True, comment='最高价格(万元)'),
    sa.Column('fuel_type', sa.Enum('ELECTRIC', 'HYBRID', 'PHEV', 'MILD_HYBRID', 'GASOLINE', 'DIESEL', name='fueltype'), nullable=False, comment='燃料类型'),
    sa.Column('seat_count', sa.Integer(), nullable=True, comment='座位数'),
    sa.Column('car_model', sa.Enum('SEDAN', 'SUV', 'MPV', 'COUPE', 'HATCHBACK', 'WAGON', 'PICKUP', name='carmodel'), nullable=True, comment='车型类别'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='车系图片URL'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_series_id'), 'car_series', ['id'], unique=False)
    op.create_index(op.f('ix_car_series_name'), 'car_series', ['name'], unique=False)
    op.create_table('car_series_scores',
    sa.Column('id', sa.Integer(), nullable=False, comment='评分ID'),
    sa.Column('car_series_id', sa.Integer(), nullable=False, comment='车系ID'),
    sa.Column('comfort_score', sa.Float(), nullable=True, comment='舒适性评分'),
    sa.Column('appearance_score', sa.Float(), nullable=True, comment='外观评分'),
    sa.Column('config_score', sa.Float(), nullable=True, comment='配置评分'),
    sa.Column('control_score', sa.Float(), nullable=True, comment='操控评分'),
    sa.Column('power_score', sa.Float(), nullable=True, comment='动力评分'),
    sa.Column('space_score', sa.Float(), nullable=True, comment='空间评分'),
    sa.Column('interior_score', sa.Float(), nullable=True, comment='内饰评分'),
    sa.Column('total_score', sa.Float(), nullable=True, comment='总分'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['car_series_id'], ['car_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_series_id')
    )
    op.create_index(op.f('ix_car_series_scores_id'), 'car_series_scores', ['id'], unique=False)
    op.create_table('complaint_data',
    sa.Column('id', sa.Integer(), nullable=False, comment='投诉数据ID'),
    sa.Column('car_series_id', sa.Integer(), nullable=False, comment='车系ID'),
    sa.Column('date', sa.String(length=7), nullable=False, comment='年月(格式: YYYY-MM)'),
    sa.Column('problem_type', sa.Enum('QUALITY', 'SERVICE', 'OTHER', name='problemtype'), nullable=False, comment='问题类型'),
    sa.Column('problem_description', sa.Text(), nullable=True, comment='问题描述'),
    sa.Column('complaint_count', sa.Integer(), nullable=True, comment='投诉量'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['car_series_id'], ['car_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='投诉数据表'
    )
    op.create_index(op.f('ix_complaint_data_car_series_id'), 'complaint_data', ['car_series_id'], unique=False)
    op.create_index(op.f('ix_complaint_data_date'), 'complaint_data', ['date'], unique=False)
    op.create_index(op.f('ix_complaint_data_id'), 'complaint_data', ['id'], unique=False)
    op.create_table('sales_data',
    sa.Column('id', sa.Integer(), nullable=False, comment='销量数据ID'),
    sa.Column('car_series_id', sa.Integer(), nullable=False, comment='车系ID'),
    sa.Column('date', sa.String(length=7), nullable=False, comment='年月(格式: YYYY-MM)'),
    sa.Column('sales_volume', sa.Integer(), nullable=True, comment='销量'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['car_series_id'], ['car_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='销量数据表'
    )
    op.create_index(op.f('ix_sales_data_car_series_id'), 'sales_data', ['car_series_id'], unique=False)
    op.create_index(op.f('ix_sales_data_date'), 'sales_data', ['date'], unique=False)
    op.create_index(op.f('ix_sales_data_id'), 'sales_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_data_id'), table_name='sales_data')
    op.drop_index(op.f('ix_sales_data_date'), table_name='sales_data')
    op.drop_index(op.f('ix_sales_data_car_series_id'), table_name='sales_data')
    op.drop_table('sales_data')
    op.drop_index(op.f('ix_complaint_data_id'), table_name='complaint_data')
    op.drop_index(op.f('ix_complaint_data_date'), table_name='complaint_data')
    op.drop_index(op.f('ix_complaint_data_car_series_id'), table_name='complaint_data')
    op.drop_table('complaint_data')
    op.drop_index(op.f('ix_car_series_scores_id'), table_name='car_series_scores')
    op.drop_table('car_series_scores')
    op.drop_index(op.f('ix_car_series_name'), table_name='car_series')
    op.drop_index(op.f('ix_car_series_id'), table_name='car_series')
    op.drop_table('car_series')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
